# Generated by Django 3.1.7 on 2021-04-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpp_tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksConnectionThemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpp_tutor.tasks')),
                ('id_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpp_tutor.themes')),
            ],
        ),
    ]
