# Generated by Django 3.1.7 on 2021-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpp_tutor', '0002_tasksconnectionthemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='difficulty',
            field=models.IntegerField(verbose_name='Количество претестов'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='theory',
            field=models.JSONField(default={}, verbose_name='Теория'),
        ),
    ]
