# Generated by Django 3.1.7 on 2021-04-21 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpp_tutor', '0005_exampletests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdicts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.TextField(default='ok', verbose_name='Вердикт')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpp_tutor.tasks')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
