# Generated by Django 3.1.7 on 2021-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpp_tutor', '0006_verdicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdicts',
            name='code',
            field=models.TextField(default='', verbose_name='Код посылки'),
        ),
    ]
